### ISSUE TITLE
Include chart title in PNG exports 

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#449] opened 2020-10-01 21:30 UTC
When creating chart widgets in a dashboard, the chart title isn't showing when you export it as PNG or SVG. Can we get the title to show?

**Comment by broncha** [comment] 2020-10-02 08:49
duplicate of https://github.com/mWater/mwater-visualization/issues/403
Closing here so we can carry on with the original one

**Closed by broncha** 2020-10-02 08:49 UTC
